### ISSUE TITLE
Cant download 

### ISSUE THREAD

**Issue by WOLFY9107** [BramDC3/smart_duel_gazer#22]
Can't download smart duel gazer every time I try to download it it says forbidden on it. It it private to to only certain people

**Comment by BramDC3** [comment]
What kind of device do you have, and which version of Android? Make sure your device supports ARCore

**Comment by WOLFY9107** [comment]
I have android 11 I should of worked

**Comment by BramDC3** [comment]
What kind of device do you have, and can you show me a screenshot?

**Comment by WOLFY9107** [comment]
![Screenshot_20210814-071146_Android System](https://user-images.githubusercontent.com/88912268/129446154-67a1fd1e-f7bf-4303-ba5f-ad22a21d39ba.jpg)

**Comment by WOLFY9107** [comment]
Gallery tab a if that what your needing

**Comment by BramDC3** [comment]
You have to allow your device to install apps outside of the store

**Comment by WOLFY9107** [comment]
Yes I have

**Comment by WOLFY9107** [comment]
I'm not sher why it says that

**Comment by WOLFY9107** [comment]
Oh to say I do have a disocod is goldddrago9107 #5033  I think
